Added template and changed vars to lowercase

diff --git a/domopicrename b/domopicrename
--- a/domopicrename
+++ b/domopicrename
@@ -1,43 +1,119 @@
 #!/usr/bin/env bash
 
-# Program version
-VERSION="v1.0"
-
-# Define colors
-COLOR_BLACK="\033[0;30m"
-COLOR_RED="\033[0;31m"
-COLOR_GREEN="\033[0;32m"
-COLOR_ORANGE="\033[0;33m"
-COLOR_BLUE="\033[0;34m"
-COLOR_PURPLE="\033[0;35m"
-COLOR_CYAN="\033[0;36m"
-COLOR_LIGHT_GRAY="\033[0;37m"
-COLOR_DARK_GRAY="\033[1;30m"
-COLOR_LIGHT_RED="\033[1;31m"
-COLOR_LIGHT_GREEN="\033[1;32m"
-COLOR_YELLOW="\033[1;33m"
-COLOR_LIGHT_BLUE="\033[1;34m"
-COLOR_LIGHT_PURPLE="\033[1;35m"
-COLOR_LIGHT_CYAN="\033[1;36m"
-COLOR_WHITE="\033[1;37m"
-
-# Define some "special" sequences
-COLOR_NONE="\033[0m"
-CLEAR_LINE="\033[1K\033[1000D"
+# Script info
+script_name="domoPicRename"
+script_version="1.1"
+script_tools="echo date figlet tput clear test mv exiftool awk tr"
 
 ########################
-# Check for parameters #
+# Definition of colors #
 ########################
 
-if [ "$1" ]; then  # Parameter given?
-  if [ "$1" = "--help" ]; then
+# General colors
+color_off="\033[0m"
+color_black="\033[0;30m"
+color_red="\033[0;31m"
+color_green="\033[0;32m"
+color_yellow="\033[0;33m"
+color_blue="\033[0;34m"
+color_purple="\033[0;35m"
+color_cyan="\033[0;36m"
+color_mark="\033[0;37m"
+color_bold_black="\033[1;30m"
+color_bold_red="\033[1;31m"
+color_bold_green="\033[1;32m"
+color_bold_yellow="\033[1;33m"
+color_bold_blue="\033[1;34m"
+color_bold_purple="\033[1;35m"
+color_bold_cyan="\033[1;36m"
+color_bold_white="\033[1;37m"
+
+# Theme colors
+color_header=$color_bold_red
+color_time=$color_bold_purple
+color_section=$color_bold_yellow
+color_mark=$color_bold_white
+color_error=$color_bold_red
+
+########################
+# Define exit function #
+########################
+
+# Function to end script with exit code and wait for ENTER to close window (if not started from shell)
+function ScriptExit()
+{
+  if [ "$script_started_in_x" = "1" ] || [ "$MC_SID" ]; then # Started in gnome-terminal or Midnight Commander?
+    if [ "$1" -ne "0" ]; then
+      echo -e "Exitcode $color_mark$1$color_off"
+    fi
+    echo
+    echo -e "Press $color_mark""ENTER$color_off to close window"
+    read
+  fi
+
+  if [ "$1" ]; then
+    exit $1
+  else
+    exit
+  fi
+}
+
+###############################
+# Handle Terminal Environment #
+###############################
+
+if [ -t 0 ] && [ -t 1 ] && [ -t 2 ]; then # STDIN, STDOUT and STDERR defined?
+  if [ "$MC_SID" ]; then # Started in Midnight Commander?
+    clear
+  fi
+  echo -en "$color_off""Running $color_mark$script_name$color_off version $color_mark$script_version$color_off"
+  if [ "$script_started_in_x" = 1 ]; then
+    echo -en " in $color_mark""X$color_off"
+  else
+    echo -en " in $color_mark""Terminal$color_off"
+    if [ "$MC_SID" ]; then # Started in Midnight Commander?
+      echo -en " started from $color_mark""mc$color_off"
+    fi
+  fi
+  echo -en " as user $color_mark$(id -un)$color_off"
+  if   [ $# -eq 1 ]; then
+    echo -e " with parameter $color_mark$@$color_off"
+  elif [ $# -gt 1 ]; then
+    echo -en " with $color_mark$#$color_off parameters$color_mark"
+    for x in "$@"; do
+      echo -en " \"$x\""
+    done
+    echo -e "$color_off"
+  else
+    echo -e " with $color_mark""no$color_off parameters"
+  fi
+else
+  # No Terminal found, starting gnome-terminal
+  gnome-terminal --title $script_name" "$script_version -- /usr/bin/env "script_started_in_x=1" "$0" "$@"
+  exit
+fi
+
+####################
+# Check Parameters #
+####################
+
+if [ $# -gt 0 ]; then # Parameter given?
+  if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
     echo "Usage: picrename [OPTIONS] FILES"
     echo
     echo "picrename will take the EXIF date from the pictures and rename the file accordingly."
     echo
     echo "Options"
-    echo "--help     This help"
-    exit 0
+    echo "-h, --help      This help"
+    echo "-d, --debug     print all executed commands"
+    echo
+    echo "Exit status:"
+    echo " 0  if OK"
+    echo " 1  if ERROR"
+    ScriptExit 0
+  elif [ "$1" = "--debug" ] || [ "$1" = "-d" ]; then
+    set -x
+    shift
   fi
 fi
 
@@ -45,91 +121,91 @@ fi
 # Check for needed tools #
 ##########################
 
-NEEDED_TOOLS="mv exiftool awk tr"
-
-for x in $NEEDED_TOOLS; do
+for x in $script_tools; do # Run through tool list
   which $x > /dev/null
   if [ $? -ne 0 ]; then
-    echo -e "Tool $COLOR_WHITE$x$COLOR_NONE is missing!"
-    exit 1
+    echo -e "Tool $color_mark$x$color_off is missing!"
+    ScriptExit 1
   fi
 done
 
-###############
-# Starting up #
-###############
+############################
+# Show script startup info #
+############################
 
-echo -ne "$COLOR_LIGHT_RED"
+echo -ne "$color_header"
+figlet $script_name -w $(tput cols)
+echo -e "$color_header$script_name $script_version$color_off"
 echo
 
-echo "     _                       ____  _      ____                                 "
-echo "  __| | ___  _ __ ___   ___ |  _ \(_) ___|  _ \ ___ _ __   __ _ _ __ ___   ___ "
-echo " / _\` |/ _ \| '_ \` _ \ / _ \| |_) | |/ __| |_) / _ \ '_ \ / _\` | '_ \` _ \ / _ \\"
-echo "| (_| | (_) | | | | | | (_) |  __/| | (__|  _ <  __/ | | | (_| | | | | | |  __/"
-echo " \__,_|\___/|_| |_| |_|\___/|_|   |_|\___|_| \_\___|_| |_|\__,_|_| |_| |_|\___|"
-echo -e "$COLOR_RED""domoPicRename $COLOR_LIGHT_RED$VERSION"
-echo -ne "$COLOR_NONE"
+##########################
+# Start time measurement #
+##########################
+
+echo -e "Starting $color_time$(date '+%Y-%m-%d %H:%M:%S')$color_off"
+script_start=$(date '+%s')
 echo
 
-###########
-# Prepare #
-###########
+##########
+# Script #
+##########
 
-# Start time
-echo -e "Starting $COLOR_LIGHT_PURPLE$(date '+%Y-%m-%d %H:%M:%S')$COLOR_NONE"
-START=$(date '+%s')
-
-################
-# Rename Files #
-################
-
-FILECOUNT=$#
-FILENUM=0
-for OLDFILE in "$@"; do
+filecount=$#
+filenum=0
+for oldfile in "$@"; do
   # Get name parts of old file
-  FILENAME="${OLDFILE##*/}"
-  DIRECTORY="${OLDFILE:0:${#OLDFILE} - ${#FILENAME}}"
-  BASENAME="${OLDFILE%.[^.]*}"
-  EXTENSION=$(echo "${OLDFILE:${#BASENAME} + 1}" | tr [:upper:] [:lower:])
+  filename="${oldfile##*/}"
+  directory="${oldfile:0:${#oldfile} - ${#filename}}"
+  basename="${oldfile%.[^.]*}"
+  extension=$(echo "${oldfile:${#basename} + 1}" | tr [:upper:] [:lower:])
 
   # Get EXIF info and build new name
-  EXIFDATE=$(exiftool -CreateDate -d "%Y-%m-%d %H.%M.%S" "$OLDFILE" 2>/dev/null | awk '{print $4 " " $5}')
-  NEWFILE="$DIRECTORY$EXIFDATE.$EXTENSION"
+  exifdate=$(exiftool -CreateDate -d "%Y-%m-%d %H.%M.%S" "$oldfile" 2>/dev/null | awk '{print $4 " " $5}')
+  newfile="$directory$exifdate.$extension"
 
   # Add number for same filenames
-  NUM=1
-  while [ -e "$NEWFILE" ]; do
-    if [ "$OLDFILE" != "$NEWFILE" ]; then
-        NUM=$((NUM+1))
-        NEWFILE="$DIRECTORY$EXIFDATE ($NUM).$EXTENSION"
+  num=1
+  while [ -e "$newfile" ]; do
+    if [ "$oldfile" != "$newfile" ]; then
+        num=$((num+1))
+        newfile="$directory$exifdate ($num).$extension"
     else
       break
     fi
   done
 
   # Handle file renaming
-  FILENUM=$((FILENUM+1))
-  echo -ne "$COLOR_YELLOW[$FILENUM/$FILECOUNT]$COLOR_NONE "
-  if [ "$EXIFDATE" != "" ]; then
-    if [ "$EXIFDATE" != "0000:00:00 00:00:00" ]; then
-      if [ "$OLDFILE" != "$NEWFILE" ]; then
-        echo -e "Renaming $COLOR_WHITE'"$(basename "$OLDFILE")"'$COLOR_NONE to $COLOR_WHITE'"$(basename "$NEWFILE")"'$COLOR_NONE"
-        mv -n "$OLDFILE" "$NEWFILE"  # -n -> do not overwrite an existing file
+  filenum=$((filenum+1))
+  echo -ne "$color_section[$filenum/$filecount]$color_off "
+  if [ "$exifdate" != "" ]; then
+    if [ "$exifdate" != "0000:00:00 00:00:00" ]; then
+      if [ "$oldfile" != "$newfile" ]; then
+        echo -e "Renaming $color_mark'"$(basename "$oldfile")"'$color_off to $color_mark'"$(basename "$newfile")"'$color_off"
+        mv -n "$oldfile" "$newfile"  # -n -> do not overwrite an existing file
       else
-        echo -e "$COLOR_WHITE'"$(basename "$OLDFILE")"'$COLOR_NONE has already the correct name!"
+        echo -e "$color_mark'"$(basename "$oldfile")"'$color_off has already the correct name!"
       fi
     else
-      echo -e "$COLOR_WHITE'"$(basename "$OLDFILE")"'$COLOR_LIGHT_RED has a bad EXIF Date!$COLOR_NONE"
+      echo -e "$color_mark'"$(basename "$oldfile")"'$color_error has a bad EXIF Date!$color_off"
     fi
   else
-    echo -e "$COLOR_WHITE'"$(basename "$OLDFILE")"'$COLOR_LIGHT_RED has no EXIF Date!$COLOR_NONE"
+    echo -e "$color_mark'"$(basename "$oldfile")"'$color_error has no EXIF Date!$color_off"
   fi
 done
 
-################
-# Finishing up #
-################
+#########################
+# Stop time measurement #
+#########################
 
-echo -e "Finished $COLOR_LIGHT_PURPLE$(date '+%Y-%m-%d %H:%M:%S')$COLOR_NONE"
-END=$(date '+%s')
-echo -e "Prog took $COLOR_LIGHT_PURPLE$(( $END - $START )) seconds$COLOR_NONE"
+echo
+echo -e "Finished $color_time$(date '+%Y-%m-%d %H:%M:%S')$color_off"
+script_end="$(date '+%s')"
+script_duration="$(( $script_end - $script_start ))"
+echo -e "Duration $color_time$script_duration sec$color_off"
+echo
+
+###############
+# Exit script #
+###############
+
+ScriptExit 0
